# Generated by Django 3.2.4 on 2021-08-18 19:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugovor',
            name='cijena_neto',
            field=models.FloatField(default=0.0, max_length=10, verbose_name='Cijena bez pdv:'),
        ),
        migrations.AddField(
            model_name='ugovor',
            name='pdv',
            field=models.FloatField(default=0.0, max_length=10, verbose_name='PDV:'),
        ),
        migrations.AlterField(
            model_name='preduzece',
            name='stopa_pdv',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='boja',
            field=models.CharField(max_length=50, verbose_name='Boja vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='broj_motora',
            field=models.CharField(max_length=50, verbose_name='Broj motora:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='broj_sasije',
            field=models.CharField(max_length=50, verbose_name='Broj šasije:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='broj_ugovora',
            field=models.IntegerField(verbose_name='Broj ugovora:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='cijena',
            field=models.FloatField(default=10.0, max_length=10, verbose_name='Cijena ugovora:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum ugovora:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='godiste',
            field=models.IntegerField(verbose_name='Godište vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='gorivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.gorivo', verbose_name='Vrsta goriva'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='grad_komitent',
            field=models.CharField(max_length=100, verbose_name='Grad:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='grad_kupac',
            field=models.CharField(max_length=100, verbose_name='Grad:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='ime_komitent',
            field=models.CharField(max_length=150, verbose_name='Ime komitenta:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='ime_kupac',
            field=models.CharField(max_length=150, verbose_name='Ime kupca:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='jib_komitent',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='nomatch', message='Duzina mora biti 13 karaktera', regex='^.{13}$')], verbose_name='JMBG/JIB komitenta:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='jib_kupac',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='nomatch', message='Duzina mora biti 13 karaktera', regex='^.{13}$')], verbose_name='JMBG/JIB kupca:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='lk_komitent',
            field=models.CharField(max_length=20, verbose_name='Lična karta komitenta:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='lk_kupac',
            field=models.CharField(max_length=50, verbose_name='Lična karta kupca:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='marka_vozila',
            field=models.CharField(max_length=100, verbose_name='Marka vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='masa_vozila',
            field=models.CharField(max_length=20, verbose_name='Masa vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='napomena',
            field=models.CharField(max_length=150, verbose_name='Napomena:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='nosivost',
            field=models.CharField(max_length=10, verbose_name='Nosivost vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='opis',
            field=models.CharField(max_length=50, verbose_name='Model vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='reg_oznaka',
            field=models.CharField(max_length=20, verbose_name='Registarska oznaka:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='sjedista',
            field=models.CharField(max_length=5, verbose_name='Broj sjedišta:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='snaga',
            field=models.CharField(max_length=10, verbose_name='Snaga motora:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='ugovor_zakljucen',
            field=models.BooleanField(default=False, verbose_name='Ugovor zaključen:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='ulica_komitent',
            field=models.CharField(max_length=100, verbose_name='Adresa komitenta:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='ulica_kupac',
            field=models.CharField(max_length=100, verbose_name='Adresa kupca:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='vrijednost_vozila',
            field=models.FloatField(max_length=10, verbose_name='Vrijednost vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='vrsta_vozila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.vrstavozila', verbose_name='Vrsta vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='zapremina',
            field=models.IntegerField(verbose_name='Zapremina motora:'),
        ),
    ]
