# Generated by Django 3.2.4 on 2021-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0002_auto_20210818_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bussines_unit_head',
            field=models.BooleanField(null=True, verbose_name='Rukovodilac poslovnice'),
        ),
    ]
