# Generated by Django 3.2.4 on 2021-08-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0003_user_bussines_unit_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bussines_unit_head',
            field=models.BooleanField(default=False, verbose_name='Rukovodilac poslovnice'),
        ),
    ]
