# Generated by Django 3.2.4 on 2021-08-27 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0004_alter_user_bussines_unit_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugovor',
            name='storno_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Datum storna'),
        ),
        migrations.AddField(
            model_name='ugovor',
            name='storno_request',
            field=models.BooleanField(default=False),
        ),
    ]
