# Generated by Django 3.2.4 on 2021-08-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0006_auto_20210828_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugovor',
            name='storno',
            field=models.BooleanField(default=False, verbose_name='Stornirano:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='storno_request',
            field=models.BooleanField(default=False, verbose_name='Potvrditi storno:'),
        ),
    ]
