# Generated by Django 3.2.4 on 2021-09-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0007_auto_20210829_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugovor',
            name='business_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.poslovnajedinica', verbose_name='Poslovna jedinica'),
            preserve_default=False,
        ),
    ]
