# Generated by Django 3.2.4 on 2022-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0008_ugovor_business_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=150, verbose_name='Broker')),
                ('mjesto', models.CharField(max_length=150, verbose_name='Mjesto')),
                ('broker_aktivan', models.BooleanField(default=False, verbose_name='Broker aktivan:')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gorivo',
            options={'verbose_name_plural': 'Tipovi goriva'},
        ),
        migrations.AlterModelOptions(
            name='poslovnajedinica',
            options={'verbose_name_plural': 'Poslovne jedinice'},
        ),
        migrations.AlterModelOptions(
            name='preduzece',
            options={'verbose_name_plural': 'Preduzeće'},
        ),
        migrations.AlterModelOptions(
            name='ugovor',
            options={'verbose_name_plural': 'Ugovori'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Korisnici'},
        ),
        migrations.AlterModelOptions(
            name='vrstavozila',
            options={'verbose_name_plural': 'Vrsta vozila'},
        ),
        migrations.AddField(
            model_name='ugovor',
            name='naplaceno',
            field=models.CharField(default='NE', max_length=2, verbose_name='Naplaćeno:'),
        ),
    ]
