# Generated by Django 3.2.4 on 2022-08-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0009_auto_20220806_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name_plural': 'Brokeri'},
        ),
        migrations.AddField(
            model_name='ugovor',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.broker', verbose_name='Broker'),
            preserve_default=False,
        ),
    ]
