# Generated by Django 3.2.4 on 2023-02-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0010_auto_20220806_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_contracts',
            field=models.BooleanField(default=False, verbose_name='Vidi ugovore'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_invoices',
            field=models.BooleanField(default=False, verbose_name='Vidi fakture'),
        ),
    ]
