# Generated by Django 3.2.4 on 2023-08-24 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0011_auto_20230225_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugovor',
            name='broj_fiskalnog_racuna',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Broj fiskalnog računa:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ugovor',
            name='broj_punomoci',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Broj punomoći:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ugovor',
            name='datum_preuzimanja',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum preuzimanja:'),
        ),
        migrations.AddField(
            model_name='ugovor',
            name='mjesto_zakljucenja',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Mjesto zaključenja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ugovor',
            name='vrijeme_preuzimanja',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Vrijeme preuzimanja:'),
        ),
    ]
