# Generated by Django 3.2.4 on 2023-09-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0012_auto_20230824_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='preduzece',
            name='broj_rjesenja',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preduzece',
            name='porezni_broj',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
