# Generated by Django 3.2.4 on 2023-09-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0014_preduzece_web_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugovor',
            name='jmb_puomocnika',
            field=models.CharField(blank=True, max_length=100, verbose_name='JMB Punomoćnika'),
        ),
        migrations.AddField(
            model_name='ugovor',
            name='lk_punomocnik',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lična karta punomoćnika'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='broj_punomoci',
            field=models.CharField(blank=True, max_length=100, verbose_name='Broj punomoći:'),
        ),
    ]
