# Generated by Django 3.2.4 on 2023-09-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0015_auto_20230917_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ugovor',
            old_name='jmb_puomocnika',
            new_name='jmb_punomocnik',
        ),
    ]
