# Generated by Django 3.2.4 on 2023-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0016_rename_jmb_puomocnika_ugovor_jmb_punomocnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugovor',
            name='broj_punomoci',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Broj punomoći:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='jmb_punomocnik',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='JMB Punomoćnika'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='lk_punomocnik',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Lična karta punomoćnika'),
        ),
    ]
