# Generated by Django 3.2.4 on 2023-09-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0017_auto_20230917_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugovor',
            name='boja',
            field=models.CharField(blank=True, max_length=50, verbose_name='Boja vozila:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='broker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.broker', verbose_name='Broker'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='gorivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.gorivo', verbose_name='Vrsta goriva'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='napomena',
            field=models.CharField(blank=True, max_length=150, verbose_name='Napomena:'),
        ),
        migrations.AlterField(
            model_name='ugovor',
            name='sjedista',
            field=models.CharField(blank=True, max_length=5, verbose_name='Broj sjedišta:'),
        ),
    ]
