# Generated by Django 3.2.4 on 2023-09-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0018_auto_20230918_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugovor',
            name='broker',
        ),
    ]
