# Generated by Django 3.2.4 on 2023-09-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0020_alter_ugovor_masa_vozila'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ime_prezime',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ime i prezime'),
        ),
    ]
