# Generated by Django 3.2.4 on 2023-10-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0021_user_ime_prezime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugovor',
            name='broj_telefona_komitent',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefon komitent:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ugovor',
            name='broj_telefona_kupac',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefon kupac:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ugovor',
            name='ima_punomoc',
            field=models.BooleanField(default=False, verbose_name='Ima punomoć:'),
        ),
    ]
