# Generated by Django 3.2.4 on 2023-10-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0022_auto_20231011_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ugovor',
            old_name='broj_telefona_komitent',
            new_name='telefon_komitent',
        ),
        migrations.RenameField(
            model_name='ugovor',
            old_name='broj_telefona_kupac',
            new_name='telefon_kupac',
        ),
    ]
