# Generated by Django 3.2.4 on 2023-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0023_auto_20231011_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugovor',
            name='ugovor_pregledan',
            field=models.BooleanField(default=False, verbose_name='Ugovor pregledan'),
        ),
        migrations.AddField(
            model_name='ugovor',
            name='zahtjev_pregled',
            field=models.BooleanField(default=False, verbose_name='Zahtjev za pregled'),
        ),
    ]
