# Generated by Django 3.2.4 on 2023-10-17 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0024_auto_20231016_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_banke', models.CharField(max_length=150, verbose_name='Naziv banke:')),
                ('sjediste_banke', models.CharField(max_length=15, verbose_name='Sjedište banke')),
                ('adresa_banke', models.CharField(max_length=150, verbose_name='Adresa banke')),
            ],
        ),
        migrations.AddField(
            model_name='ugovor',
            name='zaduzenje',
            field=models.FloatField(default=10.0, max_length=10, verbose_name='Zaduzenje'),
        ),
        migrations.CreateModel(
            name='StavkeBankovnogIzvoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=150, verbose_name='Opis')),
                ('uplata', models.FloatField(default=0.0, max_length=10, verbose_name='Uplata')),
                ('isplata', models.FloatField(default=0.0, max_length=10, verbose_name='Isplata')),
                ('korisnik_uplatio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='BankovniIzvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_izvoda', models.IntegerField(verbose_name='Broj izvoda:')),
                ('datum_izvoda', models.DateField(default=django.utils.timezone.now, verbose_name='Datum izvoda:')),
                ('napomena', models.CharField(max_length=150, null=True)),
                ('id_banke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.banka')),
            ],
        ),
    ]
