# Generated by Django 3.2.4 on 2023-10-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0025_auto_20231017_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankovniizvod',
            name='zakljucen_izvod',
            field=models.BooleanField(default=False),
        ),
    ]
