# Generated by Django 3.2.4 on 2023-10-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0026_bankovniizvod_zakljucen_izvod'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankovniizvod',
            name='poslovna_jedinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.poslovnajedinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stavkebankovnogizvoda',
            name='id_bankovni_izvod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kupoprodaja.bankovniizvod'),
            preserve_default=False,
        ),
    ]
