# Generated by Django 3.2.4 on 2023-10-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0027_auto_20231018_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankovniizvod',
            old_name='id_banke',
            new_name='banka',
        ),
    ]
