# Generated by Django 3.2.4 on 2023-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0028_rename_id_banke_bankovniizvod_banka'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresa',
            field=models.CharField(default=1, max_length=100, verbose_name='Adresa:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='broj_telefona',
            field=models.CharField(default=1, max_length=20, verbose_name='Broj telefona:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='jmb_korisnika',
            field=models.IntegerField(default=1, max_length=13, verbose_name='JMBG korisnika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='licna_karta',
            field=models.CharField(default=1, max_length=15, verbose_name='Lična karta:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mjesto',
            field=models.CharField(default=1, max_length=50, verbose_name='Mjesto:'),
            preserve_default=False,
        ),
    ]
