# Generated by Django 3.2.4 on 2023-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kupoprodaja', '0029_auto_20231021_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jmb_korisnika',
            field=models.IntegerField(verbose_name='JMBG korisnika'),
        ),
    ]
